### ISSUE TITLE
Uses old version of Geist (1.0.1)

### ISSUE THREAD

**Issue by eikowagenknecht** [contigen/non.geist#3]
I see your package uses an old version of Geist (1.0.1) instead of the latest one (1.1.0). Would be nice if you updated to the latest. Can this maybe be automated somehow?

Also it would be nicec if you mentioned the version in the README, I had to compare the files with the official downloads to find out which version it was.

**Comment by contigen** [comment]
Hi! Thanks for the info; I'll check it out later.

**Comment by eikowagenknecht** [comment]
Now the latest version is v1.3.0. Unfortunately this repo here does not seem to get any updates.

**Comment by contigen** [comment]
Hi! I was working on an update that is supposed to update the font files automatically, dropped it due to schedule. Anyways, I'll have to update the code manually for now; you could make a PR too. Thanks

**Comment by contigen** [comment]
Hey! updated to v1.3.0

**Comment by contigen** [comment]
Hey @eikowagenknecht 
Fun fact: as regards the fonts' update thingy, I need something [here](https://github.com/contigen/font-release-script)
