### ISSUE TITLE
TailwindCSS Example

### ISSUE THREAD

**Issue by Ynnck123** [contigen/non.geist#4]
I would kindly ask if it would be possible to add an example, maybe just in the documentation, on how to use the package with TailwindCSS and React ? Thank you for your efforts!

**Comment by contigen** [comment]
Hi! Like you would in a normal React app.

main.(jsx|tsx):

`import 'non.geist'`

index.css:
```
@layer base {
  :root {
    font-family: 'Geist Variable';
  }
```

or 
```
@layer base {
  body {
    font-family: 'Geist Variable';
    @apply m-4
  }
```
